# See https://github.com/actions/labeler

'🚨 action':
- .github/workflows/**

# Note: The "any" logic requires ANY file of the PR to match ALL (!) of the globs in the array,
# so to match files in multiple different paths, we also need multiple "any" arrays.
i18n:
- any: ['src/content/docs/**/*.mdx', '!src/content/docs/en/**/*']
- any: ['src/i18n/**/*', '!src/i18n/en/*']
glossary:
- any: ['src/content/docs/**/glossary.mdx']
