blank_issues_enabled: true
contact_links:
  - name: Support & Community 💁
    url: https://astro.build/chat
    about: 'This issue tracker is not for support questions. Our Discord server hosts an active community of Astro users. Come join us to discuss Astro or find assistance!'
